# Generated by Django 3.2.4 on 2023-09-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Translate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user_name',
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
