# Generated by Django 3.2.4 on 2023-09-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackdata',
            name='currenttime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feedbackdata',
            name='topic_title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
