# Generated by Django 3.2.4 on 2023-10-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0003_feedbackdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackdata',
            name='checkers_superuser',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
